//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sauna
    {
        public int SaunaId { get; set; }
        public string SaunaNimi { get; set; }
        public int VirtaStatus { get; set; }
        public int LämpöTila { get; set; }
    }
}
